
project_id = "zutwyyepahbbvrcbsbke"

[functions.openphone-webhook]
verify_jwt = false

[functions.send-sms]
verify_jwt = true

[functions.test-openphone-key]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.send-sms-with-test]
verify_jwt = false
