
zutwyyepahbbvrcbsbke = "zutwyyepahbbvrcbsbke"

[functions.health-check]
verify_jwt = false

[functions.minimal-test]
verify_jwt = false

[functions.openai-recommendations]
verify_jwt = true

[functions.openphone-webhook]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = true

[functions.send-sms-with-test]
verify_jwt = true

[functions.sms-conversation-service]
verify_jwt = true

[functions.contextual-recommendations]
verify_jwt = true

[functions.test-openphone-key]
verify_jwt = false

[functions.google-auth]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.auth-webhook]
verify_jwt = false
