
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tulhwmzrvbzzacphunes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1bGh3bXpydmJ6emFjcGh1bmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODMxNDksImV4cCI6MjA2NDU1OTE0OX0.j2k_R4gCycWClxsThIW3r6zRLdNDCMGAWDCvbT7fPq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
